# POST http://localhost:8080/authenticate
# Content-Type: application/json

# {
#     "username": "zack"
# }


POST http://localhost:8080/hostel-managers-chat
Content-Type: application/json

{
    "usernames": ["adam_la_morre", "bob_baker", "wendy_walker"],
    "title": "Another Surprise Party!",
    "is_direct_chat": false
}